/**:
  ros__parameters:
    robot:
      name: "DiffDrive"

      spawn: # Optional: Gazebo Initial Spwan Pose
        x: 5.0
        y: 5.0
        theta: 0.0

      type: "DiffDrive" # types: "DiffDrive" or "CarLike"

      model: "DiffDrive" # model: "DiffDrive" or "GoCart180"

      radius: 0.75

      wheels:
        seperation: 0.5
        radius: 0.32

      odometry:
        topic: "odom"
        frame_id: "odom"
        child_frame_id: "base_link"

      laser:
        type: "sick_tim" # sick_tim or hokuyo
        hostname: '192.168.1.204'
        frame_id: "laser"
        scan_topic: "scan"
        offset_x: 0.0
        offset_y: 0.0
        offset_z: 0.28