/**:
  ros__parameters:
    server:
      communication_range: 3.5
      lookahead_dist: 5.0

      mode: "V-PIBT" # "V-PIBT" "DTEB" "V-RVO"
      record: True
      
      subgoal_generator:
        duration: 0.05
        timeout: 1.0

        buffered_voronoi_diagram:
          min_offset: 3.0
        
        velocity_obstacle:
          timeHorizon: 0.05
        
        pibt:
          min_stopping_dist: 0.25